---
title: 'Séries Temporelles : fiche TP4'
author: "Thomas Besnier, Wilfried Heyse"
output:
  html_document:
    df_print: paged
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(echo=TRUE, eval=TRUE, message = FALSE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(plotly)
```


# Etude de processus stationnaires ARMA

Nous étudions la série chronologique disponible dans le fichier `AR.txt` contenant un processus AR. 

1. Observer les auto-corrélations empiriques (partielles ou non). Retrouvez les indices sur le type de processus.

2. Estimez les coefficients du processus (on pourra utiliser la fonction `arima` sous R ou `ARIMA` disponible dans `statsmodels.tsa.arima.model` sous Python)


3. Pour le processus AR, sachant que les coefficients choisits pour simuler le processus étaient 1 et $-\frac{1}{4}$, le processus était-il bien stationnaire ? 



4. En vous basant sur l'analyse des résidus, la modélisations semble-t-elle fidèle aux données ? 


5. Effectuez le même travail sur les processus des fichiers `MA.txt` et `ARMA.txt` 




# Prédiction d'un processus 



1. Ce processus vous semble-t-il modélisable par un processus ARMA ?

2. On travaille désormais avec la série obtenue avec la méthode des différences à la série. Combien de fois faut-il appliquer la méthode ici ?


3. En observant les auto-corrélations empiriques et auto-corrélations partielles empiriques, proposer des modèles AR(p), MA(q) ou ARMA(p,q) d’ordre faible pour modéliser cette série.

4. Estimer les paramètres du modèle sélectionné.


5. Analysez les résidus.



6. Donnez une prévision pour les 20 temps suivants de la série et représentez vos prévisions.




# Précipitations mensuelles à San Fransisco entre 1932 et 1966

Récupérer le fichier contenant les précipitations mensuelles relevées à San Fransisco entre 1932 et 1966.


1. La série semble-t-elle stationnaire ?


2. On propose de modéliser la série avec un SARIMA(2,0,0,12). Rappelez les caractéristiques de ce modèle 

3. Estimer le modèle SARIMA(2,0,0,12). Afficher et tester les résidus.


4. Prévoir les précipitations de 1964, 1965 et 1966 à partir de ce modèle et représentez les.







